- name: Setup nginx server on myserver list
  hosts:
   - devservers
  become: True

  tasks:
    - name: Install the latest version of nginx 
      command: amazon-linux-extras install nginx1 -y

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Enable service httpd, and not touch the state
      service:
        name: nginx
        enabled: yes

    - name: Check Nginx Version
      command: nginx -v

    - name: Install the latest version of nginx 
      command: systemctl status nginx
    
    - name: Read external variable file
      include_vars: vars.yaml

    - name: Ansible copy file to remote server
      copy:
        content: |
          <html>
          <head>
          <meta charset="utf-8">
          <title>タイトル</title>
          </head>
          <body>
          <h1>コンテンツを指定</h1>
          </body>
          </html>
        dest: "{{ html_path }}index.html"
        
    - name: Delete file
      file:
        path: /home/ec2-user/filemodule/
        state: absent
      register: file_dir

    - name: Print file delete status
      debug: 
        msg: "ファイルの削除に成功しました"
      when: file_dir.changed

