- name: Setup nginx server on myserver list
  hosts:
   - devservers
  become: True

  tasks:
    - name: Install the latest version of nginx 
      command: amazon-linux-extras install nginx1 -y

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Enable service httpd, and not touch the state
      service:
        name: nginx
        enabled: yes

    - name: Check Nginx Version
      command: nginx -v

    - name: Install the latest version of nginx 
      command: systemctl status nginx
    
    - name: Ansible copy file to remote server
      copy:
        content: |
          <html>
          <head>
          <meta charset="utf-8">
          <title>タイトル</title>
          </head>
          <body>
          <h1>スクリプトモジュールを利用してコピーしたページです</h1>
          </body>
          </html>
        dest: "/usr/ec2-user/index.html"
    
    - name: Run a script
      script: script.sh
      
    